version: "3"
services:
  postgres:
    image: postgres:16-alpine
    container_name: acmesky-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./acmesky.sql:/docker-entrypoint-initdb.d/acmesky.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  acmesky-api:
    image: acmesky-api
    container_name: acmesky-api
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
      - JWT_TOKEN=${JWT_TOKEN}
      - RABBITMQ=${RABBITMQ}
      - SERVER_URL=${SERVER_URL}
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default

volumes:
  postgres-data:
