version: "3"
services:
  acmesky-api:
    image: acmesky-api
    container_name: acmesky-api
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
      - JWT_TOKEN=${JWT_TOKEN}
      - RABBITMQ=${RABBITMQ}
      - SERVER_URL=${SERVER_URL}
    ports:
      - "9090:8080"
    restart: unless-stopped
    networks:
      - acmesky
      - acmesky-api

networks:
  acmesky:
    external: true
  acmesky-api:
    external: true
