info:
  contact: {}
paths:
  /v1/available-flights/:
    get:
      consumes:
      - application/json
      description: Get all available flights
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all availableFlights
      tags:
      - AvailableFlights
  /v1/available-flights/{availableFlightId}/:
    get:
      consumes:
      - application/json
      description: Get an available flight
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get an available flight
      tags:
      - AvailableFlights
  /v1/interests/:
    get:
      consumes:
      - application/json
      description: Get all interests
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all interests
      tags:
      - Interests
  /v1/interests/{interestId}/:
    get:
      consumes:
      - application/json
      description: Delete a interest
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete an interest
      tags:
      - Interests
  /v1/interests/filter/:
    post:
      consumes:
      - application/json
      description: Create a new interest
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create a new interest
      tags:
      - Interests
  /v1/journeys/:
    get:
      consumes:
      - application/json
      description: Get all journeys
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all journeys
      tags:
      - Journeys
  /v1/journeys/{journeyId}/:
    get:
      consumes:
      - application/json
      description: Get an journey
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get an journey
      tags:
      - Journeys
  /v1/login/:
    post:
      consumes:
      - application/json
      description: Make login
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Make login
      tags:
      - Users
  /v1/offers/:
    get:
      consumes:
      - application/json
      description: Get all offers
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all offers
      tags:
      - Offers
  /v1/offers/{offerId}/:
    get:
      consumes:
      - application/json
      description: Get an offer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get an offer
      tags:
      - Offers
  /v1/signup/:
    post:
      consumes:
      - application/json
      description: Make signup
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Make signup
      tags:
      - Users
  /v1/users/:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all users
      tags:
      - Users
  /v1/users/{userId}/:
    get:
      consumes:
      - application/json
      description: Get an user
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get an user
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Edit an user
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Edit an user
      tags:
      - Users
swagger: "2.0"
